Update Makefile
Fix for compiler error on raspberry PI 3 - Jessie:

/usr/bin/ld: greeter_async_client.o: undefined reference to symbol 'gpr_log'
//usr/local/lib/libgrpc.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

uname -a
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux